### ISSUE TITLE
Large differences in mapping between online and github versions of shiny app

### ISSUE THREAD

**Issue by andyptt21** [martijnmolenaar/lipidontology.com#5]
Hi there,

I'm interested in getting a list of all annotations in LION/Web associated with a list of lipids. To extract these annotations, I tried running the shiny app locally. However, I'm unfortunately I'm getting much lower mapping (59%) locally than I got online (99.7%) on the same dataset. 

Small selection of online results:

| input                          | LION ID                    | LION name    |
|:-------------------------------|:---------------------------|:-------------|
| \[\#0001\] AcCar(16:0)         | C16:0                      | LION:0002882 |
| \[\#0002\] AcCar(18:1)         | C18:1                      | LION:0002922 |
| \[\#0003\] BMP(16:0_18:0)      | BMP(16:0/18:0)             | LION:0002655 |
| \[\#0004\] BMP(16:0_20:1)      | BMP(16:0/20:1)             | LION:0002658 |
| \[\#0005\] BMP(18:0_18:1)      | BMP(18:0/18:1)             | LION:0002695 |
| \[\#0006\] BMP(18:0_18:0)      | BMP(18:0/18:0)             | LION:0002694 |
| \[\#0007\] CE(18:2)            | CE(18:2)                   | LION:0001256 |
| \[\#0008\] Cer-NDS(d18:0/16:0) | C16:0                      | LION:0002882 |
|                                | d18:0 (dihydrosphingosine) | LION:0080948 |
| \[\#0009\] Cer-NDS(d18:0/24:1) | C24:1                      | LION:0002939 |
|                                | d18:0 (dihydrosphingosine) | LION:0080948 |
| \[\#0010\] Cer-NS(d18:1/16:0)  | C16:0                      | LION:0002882 |
|                                | d18:1 (sphingosine)        | LION:0080947 |

vs. Local results:

| input               | LION ID      | LION name      |
|:--------------------|:-------------|:---------------|
| AcCar(16:0)         | not found    | not found      |
| AcCar(18:1)         | not found    | not found      |
| BMP(16:0_18:0)      | LION:0002655 | BMP(16:0/18:0) |
| BMP(16:0_20:1)      | LION:0002658 | BMP(16:0/20:1) |
| BMP(18:0_18:1)      | LION:0002695 | BMP(18:0/18:1) |
| BMP(18:0_18:0)      | LION:0002694 | BMP(18:0/18:0) |
| CE(18:2)            | LION:0001256 | CE(18:2)       |
| Cer-NDS(d18:0/16:0) | not found    | not found      |
| Cer-NDS(d18:0/24:1) | not found    | not found      |
| Cer-NS(d18:1/16:0)  | not found    | not found      |

Is there anything I can do with the github package to get the same coverage of annotations as I would get online?

**Comment by martijnmolenaar** [comment]
Hi Andy,

Sorry for this late response.
The difference between online and offline was probably caused by differences in versions. The online version has been updated regularly last few months, and the GitHub rep was not up to date yet.

Last week, I updated it to the last version, ID mapping should be the same now.

KR, Martijn

**Comment by andyptt21** [comment]
Just got around to testing and it's fixed! Thanks, sorry I took so long as well.
